### ISSUE TITLE
jsonText is not defined

### ISSUE THREAD

**Issue by pmgallo** [madskristensen/W3cValidator#1]
Hi,

I'm having an error while using the validate option from the chrome plugin. The error appears to be in the following method:

    function validate() {
        callApi(function () {
            browserLink.invoke("Report", jsonText, window.location.href, _project);
        });
    }

jsonText apparently is not defined. Strangely, I actually see the request to the w3c validation service:
https://html5.validator.nu/?out=json&level=error&laxtype=yes

It completed successfully. I don't see any warnings in the visual studio warnings window though.

I'm using  the latest version of visual studio (15.2.26430.16) and i have installed the following extensions:

https://marketplace.visualstudio.com/items?itemName=MadsKristensen.W3CValidator
https://chrome.google.com/webstore/detail/web-essentials/mghdcdlpcdiodelbplncnodiiadljhhk
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserLinkInspector2017
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensibilityTools

Thanks for you help.

**Comment by pmgallo** [comment]
Downloaded the source code, changed the function to be:

function validate() {
        callApi(function (jsonText) {
            browserLink.invoke("Report", jsonText, window.location.href, _project);
        });
    }

Generated VSIX again and it works know. Please consider this for the next release of this great extension

Regards,

Pablo

**Comment by madskristensen** [comment]
@pmgallo Thanks for the code fix 👍
